# vim: set ts=2 sw=2 tw=2:
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7/lib/python2.7/site-packages

sudo: required
matrix:
  include:
    - os: linux
      python: 3.5
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=clang
    - os: linux
      python: 3.5
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=clang
    - os: linux
      python: 3.5
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=gcc
    - os: linux
      python: 3.5
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=gcc
    - os: linux
      python: 3.5
      services: docker
      env: TEST_SUITE=benchmark
    - os: linux
      python: 2.7
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=clang
    - os: linux
      python: 2.7
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=clang
    - os: linux
      python: 2.7
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=gcc
    - os: linux
      python: 2.7
      services: docker
      env: TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=gcc
    - os: linux
      python: 2.7
      services: docker
      env: TEST_SUITE=benchmark

addons:
  apt:
    packages:
      - python-dev
      - python-numpy
      - valgrind
      - cppcheck
      - memcached
      - golang

install:
  - pip install --upgrade pip
  - pip install future
  - pip install --upgrade setuptools
  - if [ $TEST_SUITE = "unittest" ]; then pip install pytest greenify gevent; fi
  - if [ $TEST_SUITE = "benchmark" ]; then pip install python-memcached pylibmc; fi

before_script:
  - ./misc/memcached_server start

script:
  - if [ $PRJ_COMPILER = "gcc" ]; then export CC=gcc CXX=g++; fi
  - if [ $PRJ_COMPILER = "clang" ]; then export CC=clang CXX=clang++; fi
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - ./misc/memcached_server stop

deploy:
  provider: pypi
  user: yangxiufeng
  password:
    secure: Oc2qdGCFGP5W51RcdD25q0hJx1mUOWf65ph8/T7hW2N4bjz2TJPsLvf37MNi5aHum0Kvqxo6HNEn3Ea+nqL9KgjxhnjmqSezwqxpXJrHgnqPMAH7prfpPpJW9R0h3PJDutMNmhsL2xn9NJeb6LQ+y38j44n1pN2JW3t2Z3CJavA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: douban/libmc
    branch: master
